os:
  - linux
language: c
sudo: required

before_install:
  - git clone https://github.com/vitasdk/vdpm
  - cd vdpm
  - sudo ./bootstrap-vitasdk.sh
  - export VITASDK=/usr/local/vitasdk
  - export PATH=$VITASDK/bin:$PATH
  - cd ..
script:
  - make
env:
 global:
  - TOP=$PWD
  - PREFIX=$TOP/dist
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-v$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER - $TRAVIS_OS_NAME"
  - git push -q https://$TAGPERM@github.com/frangarcj/vita-fix-permissions --tags
deploy:
  provider: releases
  api_key: $OAUTH
  file: "vita_fix_perms.vpk"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true

branches:
  except:
    - /^*-v[0-9]/
